export const characters = [
    { id: "Miyabi", name: "Miyabi", img: "Character/Miyabi.png", baseCost: 150, mChoices: [0, 50, 100, 100, 125, 125, 250] },
    { id: "Yanagi", name: "Yanagi", img: "Character/Yanagi.png", baseCost: 125, mChoices: [0, 25, 50, 50, 75, 75, 150] },
    { id: "Harumasa", name: "Harumasa", img: "Character/Harumasa.png", baseCost: 75, mChoices: [0, 25, 25, 50, 75, 75, 150] },
    { id: "Sokaku", name: "Sokaku", img: "Character/Sokaku.png", baseCost: 75, mChoices: [0, 0, 0, 0, 25, 25, 25] },
    { id: "Grace", name: "Grace", img: "Character/Grace.png", baseCost: 50, mChoices: [0, 0, 25, 25, 50, 50, 75] },
    { id: "Anton", name: "Anton", img: "Character/Anton.png", baseCost: 50, mChoices: [0, 0, 0, 0, 0, 25, 25] },
    { id: "Ben", name: "Ben", img: "Character/Ben.png", baseCost: 25, mChoices: [0, 0, 0, 0, 0, 0, 0] },
    { id: "Koleda", name: "Koleda", img: "Character/Koleda.png", baseCost: 75, mChoices: [0, 0, 0, 0, 25, 25, 50] },
    { id: "Ellen", name: "Ellen", img: "Character/Ellen.png", baseCost: 75, mChoices: [0, 50, 50, 50, 75, 75, 100] },
    { id: "Rina", name: "Rina", img: "Character/Rina.png", baseCost: 75, mChoices: [0, 50, 50, 50, 75, 75, 100] },
    { id: "Lycaon", name: "Lycaon", img: "Character/Lycaon.png", baseCost: 100, mChoices: [0, 50, 50, 50, 75, 75, 100] },
    { id: "Corin", name: "Corin", img: "Character/Corin.png", baseCost: 50, mChoices: [0, 0, 25, 25, 50, 50, 50] },
    { id: "Nekomata", name: "Nekomata", img: "Character/Nekomata.png", baseCost: 50, mChoices: [0, 25, 25, 25, 25, 25, 75] },
    { id: "Billy", name: "Billy", img: "Character/Billy.png", baseCost: 50, mChoices: [0, 0, 0, 0, 25, 25, 50] },
    { id: "Nicole", name: "Nicole", img: "Character/Nicole.png", baseCost: 75, mChoices: [0, 0, 25, 25, 50, 50, 75] },
    { id: "Anby", name: "Anby", img: "Character/Anby.png", baseCost: 50, mChoices: [0, 0, 0, 0, 0, 0, 25] },
    { id: "Pulchra", name: "Pulchra", img: "Character/Pulchra.png", baseCost: 50, mChoices: [0, 0, 0, 0, 0, 0, 50] },
    { id: "Lighter", name: "Lighter", img: "Character/Lighter.png", baseCost: 125, mChoices: [0, 25, 50, 50, 50, 50, 150] },
    { id: "Burnice", name: "Burnice", img: "Character/Burnice.png", baseCost: 100, mChoices: [0, 25, 50, 50, 50, 50, 100] },
    { id: "Caesar", name: "Caesar", img: "Character/Caesar.png", baseCost: 125, mChoices: [25, 50, 50, 50, 50, 50, 100] },
    { id: "Piper", name: "Piper", img: "Character/Piper.png", baseCost: 50, mChoices: [0, 0, 50, 50, 50, 50, 75] },
    { id: "Lucy", name: "Lucy", img: "Character/Lucy.png", baseCost: 75, mChoices: [0, 0, 0, 0, 0, 0, 50] },
    { id: "Seth", name: "Seth", img: "Character/Seth.png", baseCost: 50, mChoices: [0, 0, 25, 25, 25, 25, 25] },
    { id: "Qingyi", name: "Qingyi", img: "Character/Qingyi.png", baseCost: 100, mChoices: [0, 25, 25, 50, 50, 50, 150] },
    { id: "Zhu Yuan", name: "Zhu Yuan", img: "Character/ZhuYuan.png", baseCost: 75, mChoices: [0, 25, 25, 25, 50, 50, 125] },
    { id: "Jane Doe", name: "Jane Doe", img: "Character/Jane.png", baseCost: 75, mChoices: [0, 25, 25, 50, 75, 75, 150] },
    { id: "S Anby", name: "S Anby", img: "Character/S_Anby.png", baseCost: 50, mChoices: [0, 25, 50, 50, 50, 50, 150] },
    { id: "Solider 11", name: "Solider 11", img: "Character/S11.png", baseCost: 75, mChoices: [0, 25, 25, 25, 50, 50, 150] },
    { id: "Trigger", name: "Trigger", img: "Character/Trigger.png", baseCost: 125, mChoices: [0, 50, 50, 50, 50, 50, 150] },
    { id: "Astra Yao", name: "Astra Yao", img: "Character/Yao.png", baseCost: 150, mChoices: [0, 50, 75, 75, 75, 75, 150] },
    { id: "Evelyn", name: "Evelyn", img: "Character/Evelyn.png", baseCost: 125, mChoices: [0, 50, 75, 75, 75, 75, 200] },
    { id: "Vivian", name: "Vivian", img: "Character/Vivian.png", baseCost: 100, mChoices: [0, 25, 50, 50, 50, 50, 100] },
    { id: "Hugo", name: "Hugo", img: "Character/Hugo.png", baseCost: 125, mChoices: [0, 25, 50, 50, 70, 75, 200] },
    { id: "Pan Yinhu", name: "Pan Yinhu", img: "Character/Pan.png", baseCost: 75, mChoices: [0, 25, 25, 50, 25, 25, 50] },
    { id: "Yixuan", name: "Yixuan", img: "Character/Yixuan.png", baseCost: 150, mChoices: [0, 50, 75, 75, 75, 75, 250] },
    { id: "Ju Fufu", name: "Ju Fufu", img: "Character/Fufu.png", baseCost: 125, mChoices: [0, 25, 25, 25, 75, 75, 200] },
    { id: "Yuzuha", name: "Yuzuha", img: "Character/Yuzuha.png", baseCost: 150, mChoices: [0, 25, 50, 50, 75, 75, 200] },
];

export const weapons = [
    { id: "Bashful Demon", name: "Bashful Demon", costOwner: 25, costOther: 25, ownerCharId: "Sokaku" },
    { id: "Big Cylinder", name: "Big Cylinder", costOwner: 25 , costOther: 25, ownerCharId: "" },
    { id: "Box Cutter", name: "Box Cutter", costOwner: 25, costOther: 0, ownerCharId: "Pulchra" },
    { id: "Bunny Band", name: "Bunny Band", costOwner: 25, costOther: 0, ownerCharId: "Pan Yinhu" },
    { id: "Cannon Rotor", name: "Cannon Rotor", costOwner: 0, costOther: 20, ownerCharId: "" },
    { id: "Demara Battery Mark II", name: "Demara Battery Mark II", costOwner: 25, costOther: 25, ownerCharId: "Anby" },
    { id: "Drill Rig - Red Axis", name: "Drill Rig - Red Axis", costOwner: 25, costOther: 0, ownerCharId: "Anton" },
    { id: "Electro-Lip Gloss", name: "Electro-Lip Gloss", costOwner: 0, costOther: 20, ownerCharId: "" },
    { id: "Gilded Blossom", name: "Gilded Blossom", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Housekeeper", name: "Housekeeper", costOwner: 25, costOther: 0, ownerCharId: "Corin" },
    { id: "Kaboom the Cannon", name: "Kaboom the Cannon", costOwner: 25, costOther: 25, ownerCharId: "Lucy" },
    { id: "Marcato Desire", name: "Marcato Desire", costOwner: 25, costOther: 25, ownerCharId: "" },
    { id: "Original Transmorpher", name: "Original Transmorpher", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Peacekeeper - Specialized", name: "Peacekeeper - Specialized", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Precious Fossilized Core", name: "Precious Fossilized Core", costOwner: 20, costOther: 20, ownerCharId: "" },
    { id: "Puzzle Sphere", name: "Puzzle Sphere", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Radiowave Journey", name: "Radiowave Journey", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Rainforest Gourmet", name: "Rainforest Gourmet", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Reel Projector", name: "Reel Projector", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Roaring Ride", name: "Roaring Ride", costOwner: 25, costOther: 0, ownerCharId: "piper" },
    { id: "Six Shooter", name: "Six Shooter", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Spring Embrace", name: "Spring Embrace", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Starlight Engine", name: "Starlight Engine", costOwner: 0, costOther: 20, ownerCharId: "" },
    { id: "Starlight Engine Replica", name: "Starlight Engine Replica", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Steam Oven", name: "Steam Oven", costOwner: 0, costOther: 25, ownerCharId: "" },
    { id: "Street Superstar", name: "Street Superstar", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "The Vault", name: "The Vault", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Tremor Trigram Vessel", name: "Tremor Trigram Vessel", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Unfettered Game Ball", name: "Unfettered Game Ball", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Weeping Gemini", name: "Weeping Gemini", costOwner: 0, costOther: 25, ownerCharId: "" },
    { id: "[Cinder] Cobalt", name: "[Cinder] Cobalt", costOwner: 0, costOther: 0, ownerCharId: "" },
    { id: "Blazing Laurel", name: "Blazing Laurel", costOwner: 50, costOther: 35, ownerCharId: "Lighter" },
    { id: "Deep Sea Visitor", name: "Deep Sea Visitor", costOwner: 35, costOther: 20, ownerCharId: "Ellen" },
    { id: "Elegant Vanity", name: "Elegant Vanity", costOwner: 35, costOther: 25, ownerCharId: "Astra Yao" },
    { id: "Flamemaker Shaker", name: "Flamemaker Shaker", costOwner: 35, costOther: 25, ownerCharId: "Burnice" },
    { id: "Flight of Fancy", name: "Flight of Fancy", costOwner: 35, costOther: 20, ownerCharId: "Vivian" },
    { id: "Fusion Compiler", name: "Fusion Compiler", costOwner: 25, costOther: 25, ownerCharId: "Grace" },
    { id: "Hailstorm Shrine", name: "Hailstorm Shrine", costOwner: 50, costOther: 20, ownerCharId: "Miyabi" },
    { id: "Heartstring Nocturne", name: "Heartstring Nocturne", costOwner: 50, costOther: 25, ownerCharId: "Evelyn" },
    { id: "Hellfire Gears", name: "Hellfire Gears", costOwner: 25, costOther: 25, ownerCharId: "Koleda" },
    { id: "Ice-Jade Teapot", name: "Ice-Jade Teapot", costOwner: 25, costOther: 20, ownerCharId: "Qingyi" },
    { id: "Myriad Eclipse", name: "Myriad Eclipse", costOwner: 50, costOther: 25, ownerCharId: "Hugo" },
    { id: "Qingming Birdcage", name: "Qingming Birdcage", costOwner: 50, costOther: 50, ownerCharId: "Yixuan" },
    { id: "Riot Suppressor Mark VI", name: "Riot Suppressor Mark VI", costOwner: 20, costOther: 20, ownerCharId: "Zhu Yuan" },
    { id: "Roaring Fur-nace", name: "Roaring Fur-nace", costOwner: 35, costOther: 20, ownerCharId: "Ju Fufu" },
    { id: "Severed Innocence", name: "Severed Innocence", costOwner: 35, costOther: 25, ownerCharId: "S Anby" },
    { id: "Sharpened Stinger", name: "Sharpened Stinger", costOwner: 25, costOther: 20, ownerCharId: "Jane Doe" },
    { id: "Spectral Gaze", name: "Spectral Gaze", costOwner: 35, costOther: 20, ownerCharId: "Trigger" },
    { id: "Steel Cushion", name: "Steel Cushion", costOwner: 25, costOther: 20, ownerCharId: "Nekomata" },
    { id: "The Brimstone", name: "The Brimstone", costOwner: 25, costOther: 25, ownerCharId: "Solider 11" },
    { id: "The Restrained", name: "The Restrained", costOwner: 35, costOther: 25, ownerCharId: "Lycaon" },
    { id: "Timeweaver", name: "Timeweaver", costOwner: 35, costOther: 25, ownerCharId: "Yanagi" },
    { id: "Tusks of Fury", name: "Tusks of Fury", costOwner: 25, costOther: 25, ownerCharId: "Caesae" },
    { id: "Weeping Cradle", name: "Weeping Cradle", costOwner: 25, costOther: 20, ownerCharId: "Rina" },
    { id: "Zanshin Herb Case", name: "Zanshin Herb Case", costOwner: 25, costOther: 25, ownerCharId: "Harumasa" },
];

export const GAME_PHASES = {
    MAIN: 'main',
    RESULT: 'result'
};